
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author B5B6CACE
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    ImageIcon back;
    int startbt_state=0; //0表示未开始添加，1表示正在添加
    int thread_run_state = 0;
    Runtime runtime;
    
    public MainWindow() { 
        ImageIcon icon = new ImageIcon("icon.png");
        icon.setImage(icon.getImage().getScaledInstance(32,32,Image.SCALE_DEFAULT)); 
        this.setIconImage(icon.getImage());
        back = new ImageIcon("nupt.jpg");
        back.setImage(back.getImage().getScaledInstance(170,479,Image.SCALE_DEFAULT)); 
        setResizable(false); 
        runtime = Runtime.getRuntime();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private int Start(String words,final int times){
        StringSelection stringSelection = new StringSelection(words);
        Toolkit.getDefaultToolkit().getSystemClipboard().setContents(stringSelection, null); //加入剪贴板
        
        new Thread(new Runnable(){
            public void run(){
                int loop;
                thread_run_state = 1;
                try {
                    runtime.exec("adb shell monkey -f /sdcard/bootstrap 1").waitFor();
                } catch (IOException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InterruptedException ex) {
                    Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
                for(loop = 0;loop < times;loop++){
                    if(thread_run_state == 0){
                        return ;
                    }
                    try {
                        logtext.append("I:正在向第 "+(loop+1)+" 个附近的人发送问候\n");
                        runtime.exec("adb shell monkey -f /sdcard/testmk 1").waitFor();
                    } catch (IOException ex) {
                        logtext.append("E:运行出错，请检查模拟器是否处于连接状态\n");
                        startbt.doClick();
                        return ;
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
               startbt.doClick(); 
            }}).start();
        return 0;
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlepic = new javax.swing.JLabel(back);
        jLabel1 = new javax.swing.JLabel();
        greetwords = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addtimes = new javax.swing.JTextField();
        startbt = new javax.swing.JButton();
        adbrestartbt = new javax.swing.JButton();
        exitbt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        logtext = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("楷体", 0, 14)); // NOI18N
        jLabel1.setText("输入问候语：");

        greetwords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greetwordsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("楷体", 0, 14)); // NOI18N
        jLabel2.setText("输入添加次数：");

        startbt.setBackground(new java.awt.Color(241, 241, 241));
        startbt.setFont(new java.awt.Font("楷体", 0, 24)); // NOI18N
        startbt.setText("开始添加");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });

        adbrestartbt.setBackground(new java.awt.Color(241, 240, 240));
        adbrestartbt.setFont(new java.awt.Font("楷体", 0, 14)); // NOI18N
        adbrestartbt.setText("连接模拟器");
        adbrestartbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adbrestartbtActionPerformed(evt);
            }
        });

        exitbt.setBackground(new java.awt.Color(241, 240, 240));
        exitbt.setFont(new java.awt.Font("楷体", 0, 14)); // NOI18N
        exitbt.setText("退出");
        exitbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtActionPerformed(evt);
            }
        });

        logtext.setColumns(20);
        logtext.setFont(new java.awt.Font("微软雅黑", 0, 12)); // NOI18N
        logtext.setRows(5);
        logtext.setText("使用说明：\n      将模拟器操作到微信“附近的人”页面，输入\n问候语和添加次数，点击“开始添加”即可群加好\n友。\n________________________________________________________\nLog:\n");
        jScrollPane1.setViewportView(logtext);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlepic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(adbrestartbt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(exitbt, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(startbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 10, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(greetwords)
                            .addComponent(addtimes))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(titlepic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greetwords, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addtimes, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startbt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adbrestartbt, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(exitbt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void greetwordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greetwordsActionPerformed

    }//GEN-LAST:event_greetwordsActionPerformed

    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
        // TODO add your handling code here:
        if(startbt_state == 0){
            startbt.setText("停止添加");
            startbt.setBackground(new java.awt.Color(241, 0, 0));
            startbt_state = 1;
            int times = 0;
            try{
                times = Integer.parseInt(addtimes.getText());
            }catch(NumberFormatException exc){
                logtext.append("E:错误的“添加次数”，请输入正确的数字\n");
                startbt.doClick();
                return ;
            }
            String words = greetwords.getText();
            adbrestartbt.doClick();
            Start(words,times);
        }else{
            startbt.setBackground(new java.awt.Color(241, 241, 241));
            startbt.setText("开始添加");
            startbt_state = 0;
        }
    }//GEN-LAST:event_startbtActionPerformed

    private void adbrestartbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adbrestartbtActionPerformed
        // TODO add your handling code here:
        try {
            runtime.exec("adb kill-server").waitFor();
            runtime.exec("adb start-server").waitFor();
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_adbrestartbtActionPerformed

    private void exitbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitbtActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adbrestartbt;
    private javax.swing.JTextField addtimes;
    private javax.swing.JButton exitbt;
    private javax.swing.JTextField greetwords;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea logtext;
    private javax.swing.JButton startbt;
    private javax.swing.JLabel titlepic;
    // End of variables declaration//GEN-END:variables
}
